name: Haskell Lint and Format

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.8'

      # - name: Install HLint
      #   run: cabal install hlint

      # - name: Run HLint
      #   run: |
      #     cabal exec -- hlint .

      - name: Install Ormolu
        run: cabal install ormolu

      - name: Check formatting with Ormolu
        run: ormolu --mode check $(find . -name "*.hs")

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.8'

      - name: Install dependencies
        run: |
          cabal update
          cabal install

      - name: Run tests
        run: cabal test
